import { Router } from "express";
import { query } from "../db/connection.js";
import { validate } from "../middleware/validate.js";
import { restatementQuerySchema } from "../lib/validation.js";
import type { MethodologyMetric } from "../types/index.js";

const router = Router();

const METRICS: MethodologyMetric[] = [
  {
    name: "Daily Fees (fees_usd)",
    formula: "Sum of all fees collected by the protocol from all sources",
    description: "Gross fees generated by the protocol across all products and chains. Includes trading fees, borrow interest, liquidation penalties, and all other protocol-generated fees.",
    sources: ["DefiLlama (dailyFees dimension)"],
    caveats: ["Not all protocols report all fee categories", "Community-maintained adapters may have coverage gaps"],
  },
  {
    name: "Protocol Revenue (revenue_usd)",
    formula: "daily_fees - supply_side_revenue",
    description: "Revenue retained by the protocol (treasury + token holders) after paying supply-side participants (LPs, lenders, stakers).",
    sources: ["DefiLlama (dailyRevenue dimension)"],
    caveats: ["Calculation methodology varies by protocol adapter"],
  },
  {
    name: "Token Holder Revenue (holder_revenue_usd)",
    formula: "Revenue explicitly allocated to governance/utility token holders",
    description: "The portion of protocol revenue distributed to token holders through fee sharing, buyback/burn, staking rewards from protocol revenue, or ve-model distributions. This is the core metric distinguishing productive tokens.",
    sources: ["DefiLlama (dailyHoldersRevenue dimension)"],
    caveats: [
      "Only ~50-80 top protocols have this dimension populated",
      "Buyback/burn value computed at execution price, not burn price",
      "ve-model distributions may include boosted emissions not purely from revenue",
    ],
  },
  {
    name: "Real P/E Ratio (real_pe_ratio)",
    formula: "market_cap_usd / (annualized_holder_revenue_usd)",
    description: "Market capitalization divided by annualized revenue flowing to token holders. Unlike traditional P/E which uses total protocol revenue, Real P/E reflects only the value token holders actually receive.",
    sources: ["CoinGecko (market cap)", "DefiLlama (holder revenue)"],
    caveats: [
      "Annualization uses trailing 30-day average × 365",
      "Infinite or undefined when holder revenue is zero",
      "Does not account for token emissions dilution",
    ],
  },
  {
    name: "Holder Revenue Yield (revenue_yield)",
    formula: "(annualized_holder_revenue_usd / market_cap_usd) × 100",
    description: "The effective 'dividend yield' of a token — what percentage return holders receive annually from protocol revenue distributions.",
    sources: ["CoinGecko (market cap)", "DefiLlama (holder revenue)"],
    caveats: ["Based on aggregate, not per-token calculation", "Yield may not be equally distributed among all holders"],
  },
  {
    name: "Revenue Per Holder (revenue_per_holder)",
    formula: "daily_holder_revenue_usd / total_holders",
    description: "Daily token holder revenue divided by total holder count. Indicates whether value accrual is meaningful per capita or diluted across a large holder base.",
    sources: ["DefiLlama (holder revenue)", "Codex (holder count)"],
    caveats: ["Assumes equal distribution which is rarely the case", "Actual per-holder amounts depend on balance and staking status"],
  },
  {
    name: "Productive Token Score (productive_token_score)",
    formula: "revenue_to_holders_score + mechanism_maturity_score + holder_growth_score + concentration_score",
    description: "Composite 0-10 score answering 'how effectively does this token capture and distribute protocol revenue.' Four equally-weighted components of 0-2.5 each.",
    sources: ["Computed from DefiLlama, CoinGecko, and Codex data"],
    caveats: [
      "Subjective weighting of components",
      "Score is relative to current protocol universe, not absolute",
      "Updated daily with latest available data",
    ],
  },
  {
    name: "Revenue Efficiency (holder_revenue_pct)",
    formula: "(daily_holders_revenue_usd / daily_fees_usd) × 100",
    description: "Percentage of total fees flowing through the protocol that reaches token holders. Measures the protocol's commitment to sharing value with token holders.",
    sources: ["DefiLlama (fees and holder revenue)"],
    caveats: ["Does not account for indirect benefits like governance power"],
  },
  {
    name: "Net Earnings (daily_earnings_usd)",
    formula: "daily_revenue_usd - daily_incentives_usd",
    description: "Protocol revenue minus token incentive emissions. Shows whether the protocol is profitable after accounting for the cost of token rewards used to attract users.",
    sources: ["DefiLlama (dailyEarnings dimension)"],
    caveats: ["Incentive values based on token price at time of emission"],
  },
  {
    name: "Holder Concentration (top10_pct)",
    formula: "Sum of top 10 holder balances / total supply × 100",
    description: "Percentage of token supply held by the top 10 wallets. Indicates distribution health — lower concentration generally suggests healthier distribution.",
    sources: ["Codex (holder data)"],
    caveats: [
      "Codex only captures wallets that have performed swaps",
      "Exchange wallets may represent many underlying holders",
      "Smart contract wallets (staking, governance) skew concentration metrics",
    ],
  },
];

router.get("/metrics", (_req, res) => {
  res.json({
    metrics: METRICS,
    last_updated: "2026-02-07",
    methodology_version: "1.0",
  });
});

router.get("/restatements", validate(restatementQuerySchema), async (req, res, next) => {
  try {
    const { since, page, limit } = req.query as any;
    const offset = (page - 1) * limit;

    let whereClause = "";
    const params: unknown[] = [limit, offset];
    if (since) {
      whereClause = "WHERE created_at >= $3";
      params.push(since);
    }

    const result = await query(
      `SELECT * FROM restatement_log
      ${whereClause}
      ORDER BY created_at DESC
      LIMIT $1 OFFSET $2`,
      params
    );

    const countResult = await query(
      `SELECT COUNT(*) as total FROM restatement_log ${whereClause}`,
      since ? [since] : []
    );

    res.json({
      data: result.rows,
      pagination: {
        page,
        limit,
        total: Number(countResult.rows[0].total),
      },
    });
  } catch (error) {
    next(error);
  }
});

export default router;
